interface EmployeePerformanceExportProps {
  employeeName: string;
  employeeRole: string;
  employeeEmail: string;
  summary: {
    totalLeads: number;
    wonLeads: number;
    conversionRate: number;
    totalWonValue: number;
    avgDealValue: number;
    totalOrdersCompleted: number;
    totalRevenue: number;
    avgRating: number;
    reviewCount: number;
    avgResponseTimeHours: number;
  };
  monthlyMetrics: any[];
  monthlyOrders: any[];
  monthlyReviews: any[];
  kpis?: any[];
}

export function exportEmployeePerformance(data: EmployeePerformanceExportProps) {
  const content = `
EMPLOYEE PERFORMANCE REPORT
===========================

Employee Information
--------------------
Name: ${data.employeeName}
Role: ${data.employeeRole}
Email: ${data.employeeEmail}
Report Generated: ${new Date().toLocaleString()}

Performance Summary
-------------------
Total Leads: ${data.summary.totalLeads}
Won Leads: ${data.summary.wonLeads}
Conversion Rate: ${data.summary.conversionRate}%
Total Won Value: R${data.summary.totalWonValue.toLocaleString()}
Average Deal Value: R${data.summary.avgDealValue.toLocaleString()}
Average Response Time: ${data.summary.avgResponseTimeHours.toFixed(1)} hours
Orders Completed: ${data.summary.totalOrdersCompleted}
Total Revenue: R${data.summary.totalRevenue.toLocaleString()}
Average Rating: ${data.summary.avgRating.toFixed(1)}/5 (${data.summary.reviewCount} reviews)

${data.kpis && data.kpis.length > 0 ? `
Key Performance Indicators
--------------------------
${data.kpis.map(kpi => `
${kpi.kpiName}
  Target: ${kpi.targetValue} ${kpi.unit}
  Actual: ${kpi.actualValue} ${kpi.unit}
  Achievement: ${kpi.achievementRate.toFixed(0)}%
  Period: ${new Date(kpi.periodStart).toLocaleDateString()} - ${new Date(kpi.periodEnd).toLocaleDateString()}
`).join('\n')}
` : ''}

${data.monthlyMetrics.length > 0 ? `
Monthly Lead Performance
------------------------
Period | Total | Won | Lost | Conv% | Avg Value
${data.monthlyMetrics.map(m => 
  `${m.period} | ${m.totalLeads} | ${m.wonLeads} | ${m.lostLeads} | ${m.conversionRate.toFixed(1)}% | R${Math.round(m.avgDealValue).toLocaleString()}`
).join('\n')}
` : ''}

${data.monthlyOrders.length > 0 ? `
Monthly Order Performance
-------------------------
Period | Orders | Revenue
${data.monthlyOrders.map(m => 
  `${m.period} | ${m.completedOrders} | R${Math.round(m.totalRevenue).toLocaleString()}`
).join('\n')}
` : ''}

${data.monthlyReviews.length > 0 ? `
Monthly Customer Ratings
------------------------
Period | Reviews | Avg Rating
${data.monthlyReviews.map(m => 
  `${m.period} | ${m.reviewCount} | ${m.avgRating.toFixed(1)}/5`
).join('\n')}
` : ''}

---
This report was automatically generated by the HR Management System.
  `.trim();

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `performance-report-${data.employeeName.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
