import * as XLSX from "xlsx";
import { saveAs } from "file-saver";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface ReportColumn {
  header: string;
  key: string;
  width?: number; // PDF column width percentage
  format?: (value: any, row: any) => string;
}

export interface ReportConfig {
  title: string;
  subtitle?: string;
  filename: string;
  columns: ReportColumn[];
  data: any[];
  generatedBy?: string;
}

function formatValue(col: ReportColumn, row: any): string {
  const value = row[col.key];
  if (col.format) return col.format(value, row);
  if (value === null || value === undefined) return "";
  if (typeof value === "number") return value.toLocaleString();
  if (value instanceof Date) return value.toLocaleDateString();
  return String(value);
}

export function exportToExcel(config: ReportConfig) {
  const headers = config.columns.map((c) => c.header);
  const rows = config.data.map((row) =>
    config.columns.map((col) => {
      const value = row[col.key];
      if (col.format) return col.format(value, row);
      if (value === null || value === undefined) return "";
      return value;
    })
  );

  const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);

  // Set column widths
  ws["!cols"] = config.columns.map((col) => ({
    wch: Math.max(col.header.length + 2, 15),
  }));

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, config.title.substring(0, 31));

  // Add summary sheet
  const summaryData = [
    ["Report", config.title],
    ["Generated", new Date().toLocaleString()],
    ["Total Records", config.data.length.toString()],
  ];
  if (config.subtitle) summaryData.splice(1, 0, ["Filter", config.subtitle]);
  if (config.generatedBy) summaryData.push(["Generated By", config.generatedBy]);

  const summaryWs = XLSX.utils.aoa_to_sheet(summaryData);
  summaryWs["!cols"] = [{ wch: 20 }, { wch: 40 }];
  XLSX.utils.book_append_sheet(wb, summaryWs, "Summary");

  const wbout = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  const blob = new Blob([wbout], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  saveAs(blob, `${config.filename}.xlsx`);
}

export function exportToPDF(config: ReportConfig) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(config.title, pageWidth / 2, 15, { align: "center" });

  let yPos = 22;
  if (config.subtitle) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(config.subtitle, pageWidth / 2, yPos, { align: "center" });
    yPos += 6;
  }

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated: ${new Date().toLocaleString()} | Total Records: ${config.data.length}`, pageWidth / 2, yPos, { align: "center" });
  yPos += 4;
  if (config.generatedBy) {
    doc.text(`Generated By: ${config.generatedBy}`, pageWidth / 2, yPos, { align: "center" });
    yPos += 4;
  }

  const headers = config.columns.map((c) => c.header);
  const rows = config.data.map((row) =>
    config.columns.map((col) => formatValue(col, row))
  );

  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: yPos + 2,
    theme: "grid",
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontSize: 7,
      fontStyle: "bold",
      halign: "left",
    },
    bodyStyles: {
      fontSize: 7,
      cellPadding: 2,
    },
    alternateRowStyles: {
      fillColor: [245, 245, 255],
    },
    styles: {
      overflow: "linebreak",
      cellWidth: "wrap",
    },
    columnStyles: config.columns.reduce(
      (acc, col, i) => {
        if (col.width) acc[i] = { cellWidth: col.width };
        return acc;
      },
      {} as Record<number, any>
    ),
    margin: { left: 10, right: 10 },
    didDrawPage: (data: any) => {
      // Footer with page numbers
      const pageCount = doc.getNumberOfPages();
      doc.setFontSize(7);
      doc.text(
        `Page ${data.pageNumber} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 5,
        { align: "center" }
      );
    },
  });

  doc.save(`${config.filename}.pdf`);
}
